<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.trionesdev.csi</groupId>
    <artifactId>triones-cloud-integrations</artifactId>
    <packaging>pom</packaging>
    <version>1.0-SNAPSHOT</version>
    <name>Triones:CloudIntegrations</name>
    <modules>
        <module>triones-csi-api</module>
        <module>triones-csi-api/triones-csi-api-base</module>
        <module>triones-csi-api/triones-csi-api-oss</module>
        <module>triones-csi-api/triones-csi-api-sms</module>
        <module>triones-csi-api/triones-csi-api-ocr</module>
        <module>triones-csi-aliyun</module>
        <module>triones-csi-aliyun/triones-csi-aliyun-oss</module>
        <module>triones-csi-aliyun/triones-csi-aliyun-sms</module>

        <module>triones-csi-tencentcloud</module>
        <module>triones-csi-tencentcloud/triones-csi-tencentcloud-cos</module>
        <module>triones-csi-tencentcloud/triones-csi-tencentcloud-sms</module>
        <module>triones-csi-tencentcloud/triones-csi-tencentcloud-ses</module>
        <module>triones-csi-tencentcloud/triones-csi-tencentcloud-ocr</module>

        <module>triones-csi-huaweicloud</module>
        <module>triones-csi-huaweicloud/triones-csi-huaweicloud-obs</module>
        <module>triones-csi-huaweicloud/triones-csi-huaweicloud-sms</module>

        <module>triones-csi-qiniu</module>
        <module>triones-csi-qiniu/triones-csi-qiniu-kodo</module>
        <module>triones-csi-googlecloud</module>
        <module>triones-csi-googlecloud/triones-csi-googlecloud-storage</module>
        <module>triones-csi-selfhosted</module>
        <module>triones-csi-selfhosted/triones-csi-minio</module>
        <module>triones-csi-azure</module>
        <module>triones-csi-azure/triones-csi-azure-blob</module>
        <module>triones-csi-api/triones-csi-api-ses</module>
        <module>triones-csi-dependencies</module>

    </modules>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.trionesdev.csi</groupId>
                <artifactId>triones-csi-dependencies</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <distributionManagement>
        <!--        <snapshotRepository>
                    <id>ossrh</id>
                    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
                </snapshotRepository>
                <repository>
                    <id>ossrh</id>
                    <url>https://oss.sonatype.org/service/local/staging/deploy/maven2</url>
                </repository>-->
        <snapshotRepository>
            <id>moensun</id>
            <url>https://nexus.moensun.com/repository/maven-snapshots/</url>
        </snapshotRepository>
        <repository>
            <id>moensun</id>
            <url>https://nexus.moensun.com/repository/maven-releases/</url>
        </repository>
    </distributionManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.8.1</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>2.5.3</version>
                <configuration>
                    <autoVersionSubmodules>true</autoVersionSubmodules>
                    <useReleaseProfile>false</useReleaseProfile>
                    <releaseProfiles>release</releaseProfiles>
                    <goals>deploy</goals>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>ms-repository</id>
            <url>https://nexus.moensun.com/repository/maven-public/</url>
            <layout>default</layout>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>daily</updatePolicy>
            </releases>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>ms-repository</id>
            <url>https://nexus.moensun.com/repository/maven-public/</url>
            <layout>default</layout>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>daily</updatePolicy>
            </releases>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>


</project>