<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.trionesdev.csi</groupId>
    <artifactId>csi</artifactId>
    <packaging>pom</packaging>
    <version>0.0.2-SNAPSHOT</version>
    <name>Triones:CloudIntegrations</name>
    <modules>
        <module>csi-api</module>
        <module>csi-api/csi-api-base</module>
        <module>csi-api/csi-api-oss</module>
        <module>csi-api/csi-api-sms</module>
        <module>csi-api/csi-api-ocr</module>
        <module>csi-api/csi-api-ses</module>
        <module>csi-aliyun</module>
        <module>csi-aliyun/csi-aliyun-oss</module>
        <module>csi-aliyun/csi-aliyun-sms</module>

        <module>csi-tencentcloud</module>
        <module>csi-tencentcloud/csi-tencentcloud-cos</module>
        <module>csi-tencentcloud/csi-tencentcloud-sms</module>
        <module>csi-tencentcloud/csi-tencentcloud-ses</module>
        <module>csi-tencentcloud/csi-tencentcloud-ocr</module>

        <module>csi-huaweicloud</module>
        <module>csi-huaweicloud/csi-huaweicloud-obs</module>
        <module>csi-huaweicloud/csi-huaweicloud-sms</module>

        <module>csi-qiniu</module>
        <module>csi-qiniu/csi-qiniu-kodo</module>
        <module>csi-googlecloud</module>
        <module>csi-googlecloud/csi-googlecloud-storage</module>
        <module>csi-selfhosted</module>
        <module>csi-selfhosted/csi-minio</module>
        <module>csi-azure</module>
        <module>csi-azure/csi-azure-blob</module>

        <module>csi-dependencies</module>

    </modules>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.trionesdev.csi</groupId>
                <artifactId>csi-dependencies</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

        </dependencies>
    </dependencyManagement>


    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.8.1</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>2.5.3</version>
                <configuration>
                    <autoVersionSubmodules>true</autoVersionSubmodules>
                    <useReleaseProfile>false</useReleaseProfile>
                    <releaseProfiles>release</releaseProfiles>
                    <goals>deploy</goals>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>trionesdev</id>
            <distributionManagement>
                <snapshotRepository>
                    <id>trionesdev</id>
                    <url>https://maven.cnb.cool/trionesdev/mvn/-/packages/</url>
                </snapshotRepository>
            </distributionManagement>
        </profile>
        <profile>
            <id>central</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <version>3.3.1</version>
                        <executions>
                            <execution>
                                <id>attach-sources</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <!-- （Option）2.  javadoc jar -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <version>3.5.0</version>
                        <executions>
                            <execution>
                                <id>attach-javadocs</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>1.5</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>0.7.0</version>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>central</publishingServerId>
                            <autoPublish>true</autoPublish>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>


</project>