<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.trionesdev.csi</groupId>
        <artifactId>triones-csi</artifactId>
        <version>0.0.2-SNAPSHOT</version>
    </parent>

    <artifactId>csi</artifactId>
    <packaging>pom</packaging>
    <name>Triones:CloudIntegrations</name>
    <modules>
        <module>csi-api</module>
        <module>csi-api-base</module>
        <module>csi-api-oss</module>
        <module>csi-api-sms</module>
        <module>csi-api-ocr</module>
        <module>csi-api-ses</module>
        <!--aliyun-->
        <module>csi-aliyun</module>
        <module>csi-aliyun-oss</module>
        <module>csi-aliyun-sms</module>
        <!--tencentcloud-->
        <module>csi-tencentcloud</module>
        <module>csi-tencentcloud-cos</module>
        <module>csi-tencentcloud-sms</module>
        <module>csi-tencentcloud-ses</module>
        <module>csi-tencentcloud-ocr</module>
        <!-- huaweicloud-->
        <module>csi-huaweicloud</module>
        <module>csi-huaweicloud-obs</module>
        <module>csi-huaweicloud-sms</module>
        <!-- qiniu-->
        <module>csi-qiniu</module>
        <module>csi-qiniu-kodo</module>
        <!-- googlecloud-->
        <module>csi-googlecloud</module>
        <module>csi-googlecloud-storage</module>
        <!-- azure-->
        <module>csi-azure</module>
        <module>csi-azure-blob</module>
        <!-- selfhosted-->
        <module>csi-selfhosted</module>
        <module>csi-minio</module>
    </modules>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.trionesdev.csi</groupId>
                <artifactId>csi-dependencies</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

        </dependencies>
    </dependencyManagement>

</project>